sonar.projectKey=gestion-medica-frontend
sonar.projectName=gestion-medica-frontend
sonar.host.url=http://localhost:9000
sonar.token=sqp_18cf992a7c1e14d2c43d8b5c3d1983782f42770d
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/*.test.js,**/*.test.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info