package com.SGPPiedrazul.model.enums;

public enum TipoEvento {
    USUARIO_CREADO,
    USUARIO_MODIFICADO,
    USUARIO_DESACTIVADO,
    CITA_AGENDADA,
    CITA_REAGENDADA,
    CITA_CANCELADA,
    HISTORIA_REGISTRADA,
    HISTORIA_MODIFICADA,
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    PROFESIONAL_CREADO,
    PROFESIONAL_MODIFICADO
}
