spring.application.name=Backend
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Actuator – exponer health, info y métricas Prometheus
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when_authorized
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}